# Generated by Django 5.2 on 2025-05-13 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpesarequest',
            options={'ordering': ['-timestamp'], 'verbose_name': 'M-Pesa Request', 'verbose_name_plural': 'M-Pesa Requests'},
        ),
        migrations.AlterModelOptions(
            name='mpesaresponse',
            options={'ordering': ['-timestamp'], 'verbose_name': 'M-Pesa Response', 'verbose_name_plural': 'M-Pesa Responses'},
        ),
        migrations.CreateModel(
            name='MpesaCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_code', models.CharField(max_length=10)),
                ('result_description', models.CharField(max_length=255)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='callback', to='mpesa.mpesaresponse')),
            ],
            options={
                'verbose_name': 'M-Pesa Callback',
                'verbose_name_plural': 'M-Pesa Callbacks',
                'ordering': ['-timestamp'],
            },
        ),
    ]
