# Generated by Django 5.2 on 2025-05-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0002_alter_mpesarequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesacallback',
            name='callback_metadata',
            field=models.JSONField(blank=True, help_text='Raw callback metadata from Safaricom', null=True),
        ),
        migrations.AlterField(
            model_name='mpesarequest',
            name='phone_number',
            field=models.CharField(help_text='Phone number in format 2547XXXXXXXX', max_length=15),
        ),
        migrations.AlterField(
            model_name='mpesaresponse',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mpesaresponse',
            name='customer_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mpesaresponse',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mpesaresponse',
            name='response_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mpesaresponse',
            name='response_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
